INSERT INTO project_sessions (project_name,session_date,activity_type,session_info,start_time,end_time,duration_hours,onsite_remote,stake_holders,team_members,logged_by) VALUES
('LANDMARK','10/29/24','Kick off Meeting','Initial kick of meeting','11:30','13:00',1.5,'Onsite','Ajay,Lourdes,Venkat,vinod,mohsin,Yogesh,nagaraj, Ahmed,Prasanth','Venkatesan, Ahmed Ali, Prasanth','Mohammed Nasif'),
('LANDMARK','2024-04-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-06-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-08-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-11-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/13/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/15/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-02-12','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-04-12','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-06-12','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-06-12','Sdwan Discussion','Sdwan discussion','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-09-12','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-11-12','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2024-11-12','Sdwan Discussion','Sdwan Discussion KSA sites','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed,Salman Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','12/13/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/13/24','Sdwan Discussion','Sdwan Regional Tunnel Discussion','11:30','12:30',1.0,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/16/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/16/24','Sdwan Discussion','Mother-interlinked-standalone sites discussion','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/18/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/20/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/23/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/25/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/27/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/30/24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-01-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-01','Sdwan Discussion','KSA-HO-RYD discussion','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed,Salman Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2025-03-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-06-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-01','Sdwan Discussion','Design discussion and finalization','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/13/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/13/25','Sdwan Discussion','KSA-HO Discussion','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed,Salman Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','1/15/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/16/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/17/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/20/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/21/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/22/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/23/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/24/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/27/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/28/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/29/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/30/25','HLD Doc','HLD initial draft preparation','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/20/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/22/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/22/25','Sdwan Discussion','HLD initial draft','11:00','12:00',1.0,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/23/25','Sdwan Discussion','KSA-HO-Discussion','15:00','16:00',1.0,'Remote','Ajay,Venkat,Ahmed,Salman Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','1/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/24/25','Sdwan Discussion','JADC-DR-LLD discussion','11:00','12:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/27/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/29/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/30/25','Sdwan Discussion','Initial draft review','11:00','12:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-03-02','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-05-02','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-05-02','Sdwan Discussion','KSA-HO-CCTV Traffic','11:00','12:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-02','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-02','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-02','Sdwan Discussion','Sdwan discussion','15:00','16:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-11-02','Sdwan Discussion','updated project plan','11:00','12:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-02','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-02','Sdwan Discussion','Jordan diagram and store IP','11:30','12:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/17/25','Sdwan Discussion','LLD initial draft','11:00','12:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/19/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/20/25','Sdwan Discussion','Aruba orchestrator registration','10:30','11:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/24/25','Sdwan Discussion','KSA-HO-LLD discussion','12:00','13:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/26/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/26/25','Sdwan Discussion','Documentation touchbase','14:30','15:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/27/25','Sdwan Discussion','IPS placement on Aruba sdwan','12:00','13:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/28/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-03-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-05-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-03','Sdwan Discussion','Kuwait HO discussion','10:00','10:30',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/13/25','Sdwan Discussion','Sdwan discussion with Nagaraj/Yogesh at jafza office','10:00','15:00',5.0,'Onsite','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/17/25','Sdwan Discussion','Oman design discussion','09:30','10:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/18/25','Sdwan Discussion','Bahrain design discussion','11:00','11:30',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/19/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/19/25','Sdwan Discussion','JADC EC configuration','10:00','12:00',2.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/19/25','Sdwan Discussion','JADC EC configuration','14:30','15:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/20/25','Sdwan Discussion','JADC EC configuration','14:00','15:00',1.0,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ajay,Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/24/25','Sdwan Discussion','Qatar HO Discussion','11:30','12:00',0.5,'Remote','Venkat,Ahmed, Yogesh,nagaraj, Sakib','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-04','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-09-04','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-04','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-04','Configuration','BIO Configuration','10:45','11:15',0.5,'Remote','Venkat,Nasif','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','4/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','4/16/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','4/18/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','4/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat,Nasif, Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/22/25','Bahrain-discussion','sdwan discussion','11:00','11:30',0.5,'Remote','Venkat, Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/23/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/25/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/28/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/29/25','UAE-DR-Installation','Mgmt connectivity to DR devices','11:30','13:30',2.0,'Remote','Yogesh,nagaraj, Nasif,Ahmed,Anish','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/30/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/30/25','Jordan discussion','sdwan discussion','11:00','11:30',0.5,'Remote','Yogesh,nagaraj, Nasif,Ahmed,venkat','Mohammed Nasif, Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','4/30/25','ZCC troubleshooting','Troubleshooting','12:00','12:30',0.5,'Remote','Nasif,Ahmed,Ashok','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','4/30/25','UAE DR device installation','DR EC Installation','14:00','15:30',1.5,'Remote','Nasif,Ahmed,yogesh','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-05','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-05-05','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-05','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-09-05','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-09-05','Security policy','Discussion of firewall policy','11:00','11:45',0.75,'Remote','yogesh, nagaraj, venkat, ahmed, sakib, nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-05','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Yogesh,nagaraj, Sakib,Ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-05','Kuwait Sdwan Discussion','Kuwait Sdwan Discussion','11:00','12:00',1.0,'Remote','yogesh, nagaraj, venkat, ahmed, sakib, nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/14/25','Daily Sync Call','Daily Sync Call','10:30','11:30',1.0,'Remote','darshan, nagraj, venkat, ahmed, yogesh','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','5/14/25','Site Rollout discussion','DIscussion of site rollout dates','15:30','17:30',2.0,'Remote','venkat, ahmed, Nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/14/25','Pilot Site Rollout plan','Pilot site rollout plan preperation','21:00','22:00',1.0,'Remote','Ajay, Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','5/15/25','Device Onboarding','Bahrain HO Device Onboarding','11:00','13:15',2.25,'remote','yogesh, nagaraj, venkat, ahmed, nasif, buraq ahmed','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/15/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Venkat, Ajay,Ruchika,Yogesh,nagaraj, nasif,Ahmed','Venkatesan, Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','5/16/25','Daily Sync Call','Daily Sync Call','10:30','11:10',0.67,'Remote','Ruchika, nagaraj, yogesh, venkat, ajay, ahmed, nasif, mehar','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/19/25','Daily Sync Call','Daily Sync Call','10:30','11:05',0.58,'Remote','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/19/25','Device Onboarding','ZCC Initial Device Onboarding','22:00','23:30',1.5,'Onsite','Yogesh, venkat, ruchika, nagaraj, thakiyudheen, nasif','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/20/25','Daily Sync Call','Daily Sync Call','10:00','11:00',1.0,'Remote','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/21/25','Daily Sync Call','Daily Sync Call','10:00','11:00',1.0,'Remote','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/21/25','ZCC Discussion','ZCC production deployment discussion','15:30','16:00',0.5,'Remote','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/22/25','Daily Sync Call','Daily Sync Call','10:00','11:00',1.0,'Remote','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/22/25','ZCC UAT Testing','ZCC Site UAT Testing','09:00','11:30',2.5,'Onsite','yogesh, nagaraj, venkat, ahmed, nasif,ruchika, thakiyudheen','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/23/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ruchika,venkat,ajay,ahmed,nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/23/25','Discussion','JADC Cloud discussion','11:30','12:00',0.5,'Remote','Yogesh, ahmed, nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/26/25','Migration','UAE ZCC Migration activity','01:00','15:00',14.0,'Onsite','Yogesh, ahmed, venkat, thakiyudheen, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/27/25','Daily Sync Call','Daily Sync Call','10:30','11:10',0.67,'Remote','Yogesh,ruchika,ajay, ahmed, venkat, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/28/25','Daily Sync Call','Daily Sync Call','10:30','11:10',0.67,'Remote','Yogesh,ruchika,ajay, ahmed, venkat, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/28/25','Initial Config','LMG MOE EC initial configuration','12:30','13:30',1.0,'Remote','Yogesh, ahmed, thakiyudheen','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','5/29/25','Daily Sync Call','Daily Sync Call','10:00','10:30',0.5,'Remote','Yogesh,ruchika,ajay, ahmed, venkat, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/29/25','Discussion','LMG-Gulfit-HP IDS/IPS Session','10:30','11:00',0.5,'Remote','shijeesh, nishikant, venkat, yogesh, sakib, ahmed','Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','5/29/25','Initial Config','LMG-KSA-Riyadh HO and stores initial configuration','13:00','17:30',4.5,'Remote','shaisab, yogesh, rishal, ahmed, nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/30/25','Discussion','HPE GIT LMG Discussion','09:30','10:30',1.0,'Remote','shijeesh, ahmed, venkat, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/30/25','Daily Sync Call','Daily Sync Call','10:30','11:10',0.67,'Remote','Yogesh,ruchika,ajay, ahmed, venkat, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','5/30/25','UAT testing','LMG-CPMOE Device installation and UAT testing','11:15','14:15',3.0,'Remote','Thakiyudheen, yogesh, ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ruchika,venkat,ajay,ahmed,nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-03-06','Migration','CP MOE Migration to aruba SDWAN','06:00','14:00',8.0,'Remote','Ahmed, yogesh, venkat, nagraj','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-04-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ruchika,venkat,ajay,ahmed,nasif','Venkatesan, Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-04-06','Initial Config','Kuwait HO and CP Salmiya store initial configuration','15:30','17:30',2.0,'Remote','Yogesh, malik, nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-09-06','Daily Sync Call','Daily Sync Call','10:30','10:55',0.42,'Remote','Yogesh, ruchika, nagaraj, ahmed, mujipur, nasif, Venkat','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-09-06','Initial Config','YAS MALL EC Initial config','11:30','12:00',0.5,'Remote','Yogesh, mujipur, ahmed, nasif, nagaraj','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-10-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ruchika, nagaraj, yogesh, ahmed, venkat, mujipur, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-10-06','UAT testing','YAS MALL UAT Testing','14:30','16:30',2.0,'Remote','Ahmed, nasif, yogesh, nagaraj, mujipur','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, venkat, yogesh, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-06','Configuration','SNMP, NTP,SYSLOG Configuration','11:30','13:00',1.5,'Remote','Ahmed, nasif, yogesh','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-06','Migration','YAS MALL SD-WAN Migration','06:00','10:30',4.5,'Remote/Onsite','Ahmed, nasif, yogesh, mujipur, nagaraj, ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, nagaraj, mujipur, ruchika, meharunnisa','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/13/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, ruchika, yogesh, mujipur','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','6/13/25','Discussion','Oasis and IBN discussion','09:00','10:00',1.0,'Remote','Ahmed, venkat, yogesh, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/13/25','Documentation','MoE, Yas mall deployment results documentation','15:00','17:00',2.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/16/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, venkat, ruchika, yogesh, nagaraj','Mohammed Nasif, Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/17/25','Testing','Failover testing of Uae MOE','06:00','07:00',1.0,'Remote','Nasif, yogesh, mujipur','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/17/25','Discussion','CP-IBN Migration discussion','14:00','15:00',1.0,'Remote','Nasif, venkat, yogesh, mujipur','Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/18/25','Migration','IBN MAX CP EC Migration activity','05:30','15:30',10.0,'Remote','Nasif, yogesh, mujipur, venkat, ahmed','Mohammed Nasif, Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','6/17/25','Daily Sync Call','Daily Sync Call 17th/18/19/20','07:00','11:00',4.0,'Remote','Ahmed, nasif, yogesh, nagaraj, ajay','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/23/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, nagaraj, ajay','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','6/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/23/25','Initial Config','Bahrain pilot store setup','11:00','13:30',2.5,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','6/24/25','Documentation','MOE deployment results documentation','13:00','14:00',1.0,'Remote','nasif,venkat','Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/25/25','Documentation','MOE,YAS Mall deployment results documentation','09:00','10:00',1.0,'Remote','Nasif, venkat','Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/25/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, venkat, ahmed, yogesh, ruchika','Mohammed Nasif, Venkatesan, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','6/25/25','Discussion','Deployment Discsussion','11:30','12:15',0.75,'Remote','venkat, nasif, ahmed, yogesh','Venkatesan, Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','6/26/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/27/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/30/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','6/30/25','Troubleshooting','Bahrain store testing','11:00','12:30',1.5,'Remote','yogesh, ahmed,','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-01-07','Migration','Qatar-MAX Rayaan mall migration','07:30','11:30',4.0,'Remote','ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-07','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-02-07','Testing','KWT CP Salmiya store testing','11:30','13:30',2.0,'Remote','ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-03-07','Daily sync call','Daily sync call','10:00','11:00',1.0,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-04-07','Daily sync call','Daily sync call','10:00','11:00',1.0,'Remote','Ahmed, nasif, venkat, meharunnisa, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-04-07','Discussion','KWT HO LAN discussion and VRRP configuration','11:30','12:30',1.0,'Remote','Ahmed, venkat, yogesh, nasif, nagraj','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-07-07','Migration','KWT CP Salmiya Migration to SD-WAN','07:30','11:00',3.5,'Remote','Ahmed,yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-08','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-08','Testing','Riyadh CP Wadi Laban store testing','13:00','15:00',2.0,'Remote','yogesh, ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-09','Migration','Riyadh CP Wadi Laban store migration to SD-WAN','08:00','11:30',3.5,'Remote','Yogesh, ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-14','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-14','Migration','Jafza store LAB migration to production device','12:30','13:30',1.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-14','Discussion','KSA MPLS Readiness Discussion','15:00','17:00',2.0,'Remote','Ahmed,yogesh,venkat,salman','Ahmed Ali, Venkatesan, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2025-07-15','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-15','Configuration','SSL Cert Import on Aruba Orchestrator','16:00','16:30',0.5,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-15','Discussion','Aruba SDWAN Setup discussion in Jordon','11:30','13:00',1.5,'Remote','Ahmed,yogesh,venkat','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-16','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-17','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-17','Design discussion','LMG-JORDAN-DISCUSSION','16:00','16:30',0.5,'Remote','Ahmed,yogesh,venkat','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-18','Weekly call','LMG WSR','10:00','10:30',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-18','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-21','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, venkat, ajay, ruchika, nagaraj, yogesh','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-22','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-22','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-23','Configuration','Kuwait CP salmiya store internet routing','10:00','10:30',0.5,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-23','Configuration','MFA Enablement on orchestrator','13:30','14:30',1.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-24','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-24','Troubleshootng','Riyadh Store Device in Maintenance Mode','12:30','13:30',1.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-24','Troubleshootng','Case #[20250724-432912]: LMG-KSA- Store-Device-not getting gui access','14:30','16:30',2.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-25','Weekly call','WSR','11:00','11:30',0.5,'Remote','Ahmed, saicharan','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-28','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-28','Troubleshootng','LMG-QATAR-TSHOOT','12:30','13:30',1.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-28','Sync up call','LMG-Touch-Base','15:00','15:30',0.5,'Remote','Ahmed, venkat, shijeesh','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-29','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-29','Discussion','LMG-Solarwinds reports discussion','12:00','12:30',0.5,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-29','Testing/UAT','KSA Riyadh Max & CP Batha Store Testing','14:00','16:00',2.0,'Remote','Ahmed, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-30','Migration','KSA Riyadh Max & CP Batha Store migration to Aruba SDWAN','10:30','13:00',2.5,'Remote','Ahmed,yogesh,afsal','Ahmed Ali, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-07-31','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh, venkat,shijeesh','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-31','Report Discussion','LMG-Aruba-Pilot Sites Deployment Report Discussion','14:00','15:00',1.0,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh, venkat,shijeesh, nasif','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-08-01','Weekly call','WSR','11:00','11:30',0.5,'Remote','Ahmed, saicharan','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-01','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh, venkat','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-08-04','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,  ajay, ruchika, nagaraj, yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-05','Migration','KSA SPLASH AVENUE STORE migration','09:30','13:00',3.5,'Remote','Afsal, Ahmed','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-05','Run Book Preperation','KSA Batha and Splash Avenue Store','16:00','16:30',0.5,'Remote','Afsal, Ahmed','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-06','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, yogesh, ruchika , sakeb','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-07-08','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, venkat, yogesh, sakib','Mohammed Nasif, Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-07-08','Documentation','Deployment report fine tuning','09:00','14:00',5.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-08','Migration','DFC Store migration activity','07:00','11:00',4.0,'Remote','Ahmed, nasif, yogesh, sakib, ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-08','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, venkat, yogesh, ruchika, nagraj','Ahmed Ali, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-12-08','Troubleshooting call','CP IBN Packet Loss Troubleshooting','12:30','16:30',4.0,'Remote','Ahmed,yogesh,venkat,aruba tac','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-12-08','Troubleshooting call','LMG-O365 ISSUE','12:00','12:30',0.5,'Remote','Ahmed,yogesh,aruba tac','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/13/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/13/25','LMG Quick Connect','Quick connect','13:30','14:00',0.5,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/14/25','Site Discussion','LMG-OASIS-DISCUSSION','10:00','10:30',0.5,'Remote','Ahmed,yogesh,venkat','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','8/15/25','LMG-WSR','WSR','09:30','10:00',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/15/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/15/25','Report Discussion','LMG-REPORT-Quick check','19:30','20:30',1.0,'Remote','Ahmed, Shijeesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/18/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/18/25','Configuration','LMG-IPS/IDS-Enablement & SolarWinds use cases','15:00','16:00',1.0,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/19/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/20/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/20/25','Initial Config','Oasis Dubai - LAN WAN Connections and Device Upgrade','14:30','16:30',2.0,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/21/25','Configuration','Oasis Aruba SDWAN Setup','11:00','15:00',4.0,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/22/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/22/25','LMG WSR','LMG WSR','11:30','12:00',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/22/25','LMG signoff milestone 3','LMG signoff milestone 3 doc','11:30','12:00',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/22/25','Configuration','IPSEC Setup for Oasis Hospitality','15:00','17:00',2.0,'Remote','Ahmed, Yogesh, TAC','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/25/25','Testing','Infor Tunnel Setup and Testing','08:00','09:00',1.0,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/25/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/26/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/26/25','Documentation','Checklist and SOP','11:00','15:00',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/27/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, yogesh, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/28/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, yogesh, ruchika','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','8/28/25','Documentation','SOP Document preperation','09:00','12:00',3.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','8/29/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-01-09','Documentation','LLD Document preperation','09:00','13:00',4.0,'Remote','nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-01-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-03-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-04-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-05-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, ahmed, ruchika, ajay, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-02-09','Documentation','LLD Document preperation','11:00','14:00',3.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-08-09','Daily Sync Call','Daily Sync Call','10:30','10:45',0.25,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-09-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-10-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-09','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/15/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/16/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/18/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/19/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/14/25','Testing','Testing between JORDAN DC and store','11:00','16:30',5.5,'Remote','Afsal, Nasif, Sakib, Rishal and Nagaraj','Mohammed Afsal, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/15/25','activity','JORDAN MAX PAVILION SITE','06:00','12:30',6.5,'Remote','Afsal, Nasif, Venkat, Nagaraj, Rishal, Ruchika','Mohammed Afsal, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','9/15/25','Testing','BAHRAIN store EC onboarding','15:00','17:30',2.5,'Remote','Afsal, Nasif, Rakesh and Sakib','Mohammed Afsal, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/16/25','activity','BAHRAIN store migration','05:00','09:00',4.0,'Remote','Afsal, Nasif, Rakesh, Sakib, Nagaraj','Mohammed Afsal, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/16/25','Device Onboarding','Jordan Makka store','15:00','17:30',2.5,'Remote','Afsal, Nasif, Naveen and Sakib','Mohammed Afsal, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/17/25','activity','Jordan Makka store migration','07:30','10:30',3.0,'Remote','Afsal, Nasif, Venkat, Nagaraj, Rishal, Ruchika','Mohammed Afsal, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','9/18/25','activity','Jordan City Max store migration','08:00','11:30',3.5,'Remote','Afsal, Nasif, Venkat, Nagaraj, Rishal, Ruchika,sakib,Naveen','Mohammed Afsal, Mohammed Nasif, Venkatesan','Mohammed Nasif'),
('LANDMARK','9/19/25','Migration','Jordan Warehouse migration','09:30','11:30',2.0,'Remote','Ahmed,Nasif, afsal,venkat, sakib, nagaraj, rishal','Ahmed Ali, Mohammed Nasif, Mohammed Afsal, Venkatesan','Mohammed Nasif'),
('LANDMARK','9/19/25','Device Onboarding','Jordan store Max Istiklal initial Config','16:00','16:30',0.5,'Remote','Nasif, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/22/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/23/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/25/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/26/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif, sakib , nagarja , ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/24/25','Activity','UAE-Oasis Mall migration','02:00','07:30',5.5,'Remote/Onsite','Nasif,Ahmed,venkat,yogesh','Mohammed Nasif, Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','9/21/25','Activity','Bahrain City Center Store','05:00','08:00',3.0,'Remote','Afsal, Sakib, Rishal, Nagaraj','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/21/25','activity','Jordan Max Istiklal Store','08:30','10:30',2.0,'Remote','Afsal, Sakib, Rishal, Nagaraj','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/22/25','Activity','Bahrain Raffa Store','05:00','08:00',3.0,'Remote','Afsal, Sakib, Rishal, Nagaraj','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/22/25','Device Onboarding','Bahrain and Jordan Store','14:00','18:00',4.0,'Remote','Afsal, Sakib, Rishal, Naveen and Rakesh','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/23/25','Activity','Bahrain Sagaya Store Migration','05:00','08:00',3.0,'Remote','Afsal, Sakib, Rishal, Nagaraj and Rakesh','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/23/25','Activity','Bahrain Hamad Town Store','11:00','13:00',2.0,'Remote','Afsal, Sakib, Rishal, Nagaraj and Rakesh, Afzal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/24/25','Activity','Jordan MAX Iribid Store','08:30','10:30',2.0,'Remote','Afsal, Sakib, Rishal, Nagaraj and Naveen','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/24/25','Activity','Bahrain Warehouse','16:00','22:00',6.0,'Remote','Afsal, Ahmed, Sakib,Rakesh, Afzal, Rishal, Nagaraj','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','9/25/25','Activity','Jordan Max Galleria','08:30','10:00',1.5,'Remote','Afsal, Sakib, Rishal, Nagaraj and Naveen','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/25/25','Device Onboarding','Jordan warehouse devices onboarding','17:00','19:30',2.5,'Remote','Nasif, sakib, nagaraj','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/29/25','Daily Sync Call','Daily Sync Call','10:30','11:20',0.83,'Remote','Ahmed, nasif, nagraj, ruchika, sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/29/25','KSA Cloud Proxy Test Call','KSA Cloud Proxy Test Call','14:00','15:30',1.5,'Remote','Afsal, Rishal, Nihad and Syed (Microland)','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','9/29/25','JOR WH activity','JOR WH activity','16:00','18:00',2.0,'Remote','Afsal, Ahmed, Sakib,Rakesh, Afzal, Rishal, Nagaraj','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','9/30/25','activity','BAH 3 store migration with HO','06:00','07:30',1.5,'Remote','Afsal, Ahmed,Nagaraj, Rakesh','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','9/30/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/30/25','Documentation','LLD Document preperation','11:30','13:30',2.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','9/30/25','Troubleshooting','Bahrain WH internet slowness','11:00','13:30',2.5,'Remote','Afsal, Ahmed, Sakib,Rakesh, Afzal, Rishal, Nagaraj','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-01-10','Meeting','Store Policy for Back Office and Wi-Fi SSID','11:00','12:00',1.0,'Remote','Ahmed, Afsal, Ruchika and Afzal','Ahmed Ali, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-01-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-02-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-03-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-06-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-07-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-08-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-09-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-10-10','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-02-10','Documentation','KSA stores LLD preperation','09:00','11:00',2.0,'Remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-08-10','Meeting','LMG WH FW policies for BAH and JOR','11:00','13:00',2.0,'Remote','Afsal,Ahmed, Rishal, Nagaraj and Afzal','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-08-10','Troubleshooting','BAH WH TS call','14:00','19:30',5.5,'Remote','Afsal, Venkat, Abhinesh, Nagaraj, Rishal, Afzal, Rakesh','Mohammed Afsal, Venkatesan','Mohammed Nasif'),
('LANDMARK','2025-09-10','Troubleshooting','BAH WH TS call','09:00','10:00',1.0,'Remote','Afsal, Ahmed, Sakib,Rakesh, Afzal, Rishal, Nagaraj, Vigneshwaran','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/13/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/14/25','Training','Handover session #1 for SDWAN with Gulf IT team - TCS','11:00','12:00',1.0,'Remote','Ahmed, LMG Team','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/14/25','Training','Handover session #2 for SDWAN with Gulf IT team - TCS','11:00','12:00',1.0,'Remote','Ahmed, LMG Team','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/15/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/15/25','Testing','Oasis - DMS Tunnel Testing for Hospitality','12:00','13:00',1.0,'Remote','Ahmed, Yogesh','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/16/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Venkat, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/14/25','Documentation','BAH LLD prepration','09:00','13:00',4.0,'Remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/16/25','Troubleshooting','BAH WH TS call','10:00','11:00',1.0,'Remote','afsal, ahmed, Sakib, Vignesh, Afzal','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/16/25','Device Onboarding','RIYADH Store Onboarding','11:00','13:00',2.0,'Remote','Afsal, Sakib, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/18/25','Migration','MAX U STORE migration','11:00','13:00',2.0,'Remote','Afsal, Rishal and Shaisab','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/19/25','Troubleshooting','RIYADH store NTP unreachable','15:00','16:00',1.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/20/25','Troubleshooting','RIYADH Store Access issue','09:00','10:00',1.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/20/25','Troubleshooting','RIYADH Store Access issue','15:00','16:30',1.5,'Remote','Afsal, Rishal and Shaisab','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/20/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/22/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/23/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/21/25','Troubleshooting','KSA SDWAN-Cloud proxy and BAH store access issues','10:00','11:15',1.25,'Remote','Afsal, Rishal, Afzal, Ruckika','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/27/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/28/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/29/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/30/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/31/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','10/27/25','troubleshooting','BAH LM_RETAIL android app issue','14:30','16:00',1.5,'Remote','Afsal, Ahmed, Sakib, Ruchika, Rakesh, Nagaraj','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/27/25','troubleshooting','JOR WH AP cloud issue','16:00','16:45',0.75,'Remote','Afsal, Sakib, Naveen','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/28/25','Troubleshooting','BAH LM_RETAIL android app issue','11:00','12:45',1.75,'Remote','Afsal,Ahmed,Nagaraj,Trupti,Rakesh','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','10/28/25','Configuration','JOR DHCP sever configuration','16:00','16:30',0.5,'Remote','Afsal, Naveen, Sakib, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','10/30/25','Onboarding','Dammam HO devices onboarding','11:30','12:30',1.0,'Remote','Afsa, Rishal, Sakib, Shaisab','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-03-11','Device upgradation','Riyadh store devices','15:00','17:00',2.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-02-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-03-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-04-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-05-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-06-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-05-11','troubleshooting','BAH App issue TS call','14:00','16:30',2.5,'remote','Afsal,Ahmed,Nagaraj,Abhinesh','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-10-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-11-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-11','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','11/13/25','troubleshooting','Bahrain android issue','15:30','16:30',1.0,'remote','Ahmed, Afsal, Ruchika and Afzal','Ahmed Ali, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','11/13/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','11/14/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, nasif,ruchika, nagaraj,sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','11/17/25','Oman SDWAN','Oman sdwan','11:30','12:30',1.0,'remote','Ahmed, ruchika, Venkat','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','11/17/25','Onboarding','OMAN HUB Devices','15:00','16:00',1.0,'remote','Afsal, Ahmed, Haneef and Sakib','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/17/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/18/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/19/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/20/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/21/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/24/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/25/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,ruchika, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/18/25','Design discussion','LMG-OMAN-HO-Design-Discussion-Place-Holder','12:00','13:00',1.0,'Remote','Ahmed,Venkat,nagaraj,afzal','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','11/18/25','Design discussion','discussion on DR SDWAN/Oman','17:00','18:00',1.0,'Remote','Ahmed,Venkat,nagaraj,afzal','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','11/18/25','Onboarding','OMAN WH Devices','11:00','12:30',1.5,'remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','11/19/25','Design discussion','LMG-KSA-JED-DAM-RYD-Design-Discussion','11:00','12:30',1.5,'remote','Ahmed,Venkat,Salman,nagaraj,afzal','Ahmed Ali, Venkatesan, Salman Aziz','Mohammed Nasif'),
('LANDMARK','11/20/25','Add WAN link','500mbps link in RYD HO','10:30','12:30',2.0,'remote','Afsal, ahmed, shaisab, nagaraj','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/24/25','Onboarding and upgradation','KSA store device onboarding and upgradation','11:30','18:00',6.5,'remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','11/25/25','Design discussion','ARUBA-LMG-Data-domain-discussion','11:30','12:30',1.0,'remote','Ahmed, venkat, shijeesh, Afzal,Nagaraj','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','11/25/25','Configuration','LMG-BHRAIN-BATELCO','15:30','17:30',2.0,'remote','Ahmed,sakib,Nagaraj','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/26/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed,Afzal, nagaraj,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','11/25/25','Onboarding','KSA store device onboarding and upgradation','11:00','17:00',6.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','11/26/25','Onboarding','KSA store device onboarding and upgradation','11:00','17:00',6.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2025-03-12','TAC Call','20251130-448271 : EC devices upgraded without manual upgrade | LANDMARK GROUP','12:30','13:30',1.0,'Remote','Salman','Salman Aziz','Mohammed Nasif'),
('LANDMARK','2025-12-08','Oboarding','ARUBA SDWAN RYD-DMM-JED Inter Region Connectivity','10:30','14:30',4.0,'Remote','Ahmed, nasif, rishal, nagaraj, ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-08','Oboarding','ARUBA SDWAN RYD-DMM-JED Inter Region Connectivity','15:30','19:00',3.5,'Remote','Ahmed, rishal, nagaraj, ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-09','Configuration','CP Wadi Roll back store Migration','08:00','10:00',2.0,'Remote','Ahmed, rishal, nagaraj, ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-09','Configuration','ARUBA SDWAN RYD-DMM-JED MPLS Integration','10:30','18:00',7.5,'Remote','Ahmed, rishal, nagaraj, ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-10','Configuration','ARUBA SDWAN RYD-DMM-JED MPLS Integration','08:00','17:30',9.5,'Remote','Ahmed, Nasif, rishal, nagaraj, ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-11','Configuration','ARUBA SDWAN RYD-DMM-JED MPLS Integration','09:00','17:00',8.0,'Remote','Ahmed, rishal, nagaraj, ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2025-12-10','Configuration','Oman store devices upgradation','13:30','17:30',4.0,'Remote','Nasif, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2025-12-12','Daily Sync Call','Daily Sync Call','22:30','23:00',0.5,'Remote','Ahmed, nasif, nagaraj, ruchika','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/14/25','Configuration','KSA Roll out','07:00','16:00',9.0,'Remote','Ahmed, Rishal,shaisaab','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/15/25','Troubleshooting','SD- WAN | Netskope | Someford','14:30','16:00',1.5,'Remote','Ahmed, Rishal,Nishi','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/16/25','Migration','KSA max Malaz lulu, max al nadeem riyadh  store migration','08:00','12:00',4.0,'Remote','Ahmed, rishal, nasif, nagraj','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/16/25','Upgradation','Oman devices upgradation','14:00','14:30',0.5,'Remote','Nasif, sakib, jayaraj','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/17/25','Migration','KSA Sites, MAX Nakheel Mall & MAX-Garanada migration activity','08:00','11:00',3.0,'Remote','Ahmed, rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/17/25','Discussion','LMG-ARUBA SDWAN RYD-DMM-JED Inter Region Connectivity Discussion','15:00','16:00',1.0,'Remote','Ahmed,salman,venkat,LMG','Ahmed Ali, Salman Aziz, Venkatesan','Mohammed Nasif'),
('LANDMARK','12/17/25','Troubleshooting','LMG-KSA-AVAYA-TS','20:00','21:00',1.0,'Remote','Ahmed, rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/18/25','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif, nagaraj, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/18/25','Troubleshooting','SNMP issue, Bahrain and jordan troubleshooting','11:00','11:30',0.5,'Remote','Nasif, Sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/18/25','WSR','WSR','09:00','09:30',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/20/25','Migration','KSA Sites roll out','07:30','12:45',5.25,'Remote','Ahmed,Nasif,Rishal','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/20/25','Migration','KSA Sahara and atyaf store migration, Dammam R2 Router configuration.','07:30','16:00',8.5,'Remote','Ahmed,Nasif,rishal','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/21/25','Migration','KSA cp takasusi, abha','07:30','16:00',8.5,'Remote','Ahmed,Nasif,rishal','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/21/25','configuration','Jeddah Hub routes analysis','16:00','17:00',1.0,'Remote','Ahmed, Salman','Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','12/22/25','Migration','KSA RIYADH HC Khurais migration activity','08:00','10:00',2.0,'Remote','Ahmed,Rishal,Nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/23/25','Migration','KSA Riyadh-Park store migration','08:00','10:30',2.5,'Remote','Ahmed,Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/23/25','Configuration','Oman HO devices initial configuration','11:30','14:00',2.5,'Remote','Ahmed,Sakib,Haneef,Nasif,Afsal','Ahmed Ali, Mohammed Nasif, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','12/24/25','Migration','Riyadh max shahad centre','08:00','10:00',2.0,'Remote','Ahmed,rishal, nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/25/25','Troubleshooting','Riyadh store security policy troubleshooting','17:00','17:30',0.5,'Remote','Nasif,rishal,ahmed','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/27/25','Migration','60436-Max Khaleej Mall','08:00','10:30',2.5,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/28/25','Migration','21052 – CP Othaim Khurais','08:00','10:30',2.5,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/29/25','Configuration','KSA SDWAN ACL to Prefix List Conversion in HO CSW','02:00','05:00',3.0,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/30/25','Troubleshooting','SD- WAN | Netskope | Session 3','12:30','13:30',1.0,'Remote','Ahmed,Rishal,Nishikant','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/30/25','Troubleshooting','Configuration issue with TAC team','14:00','15:00',1.0,'Remote','Rishal, Ahmed, Trupti, Nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/30/25','Configuration','LMG prefix list addtion jeddah','16:15','19:00',2.75,'Remote','rishal, ahmed, shaisab, nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/30/25','Troubleshooting','[20251224-451063]: LMG-ORCHETRATOR-subnet addition','15:00','16:00',1.0,'Remote','Rishal, Ahmed, Trupti, Nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','12/29/25','Migration','21239 CP Thumamah','08:00','11:30',3.5,'Remote','Ahmed,Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/31/25','Migration','Badiya,Al hamra,CPD Shifa','08:00','14:30',6.5,'Remote','Ahmed,Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/31/25','Configuration','LMG-PREFIX-LIST-ADDITION-Dammam','16:00','19:00',3.0,'Remote','Ahmed,Rishal, shaisab','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/27/25','Documentation','SOP Document preperation','13:30','15:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/28/25','Documentation','SOP Document preperation','14:30','15:30',1.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/29/25','Documentation','SOP Document preperation','14:30','15:30',1.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/30/25','Documentation','SOP Document preperation','14:30','15:30',1.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/31/25','Documentation','SOP Document preperation','14:30','15:30',1.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/28/25','Documentation','HLD with All territory Hos','15:30','17:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/29/25','Documentation','HLD with All territory Hos','15:30','17:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/30/25','Documentation','HLD with All territory Hos','15:30','17:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','12/31/25','Documentation','HLD with All territory Hos','15:30','17:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-03-01','Migration','21495-CP Panorama mall','08:00','12:00',4.0,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-04-01','Migration','21195 CP Saud Street','08:00','12:00',4.0,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-04-01','Documentation','LLD with All KSA Hos','13:30','17:30',4.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-05-01','Migration','60127 Max Khobar Corniche, Max Flamingo Mall Jeddah','08:00','13:30',5.5,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-05-01','Discussion','Aruba SDWAN discussion Kuwait Store','13:30','14:30',1.0,'Remote','Ahmed,Yogesh,Nasif,Sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-05-01','troubleshooting','Web Application Slowness in Jordon Store post Aruba Migration','14:30','16:00',1.5,'Remote','Ahmed, Yogesh,Jordan team','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-06-01','Migration','30095 Bossini Rahmaniya, 30204 Splash Taiba Mall','08:00','12:00',4.0,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-06-01','Documentation','LLD with All KSA Hos','15:30','17:30',2.0,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-07-01','Migration','60128 Max Dammam Corniche, 21188-CP Obhur','08:00','10:30',2.5,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-07-01','Documentation','ISP Name mapping detaills sheet','14:30','16:30',2.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-09-01','Troubleshooting','Tunnel summary issue troubleshooting with TAC','10:30','11:00',0.5,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-08-01','Troubleshooting','Peer Priority Validation Required from EC towards HO CSW','09:00','10:00',1.0,'Remote','Ahmed, Venkat,Salman,Rishal, nagaraj','Ahmed Ali, Venkatesan, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2026-08-01','Daily Sync Call','Daily Sync Call','10:30','11:30',1.0,'Remote','Ahmed, Venkat,Ajay, LMG','Ahmed Ali, Venkatesan','Mohammed Nasif'),
('LANDMARK','2026-08-01','Configuration','Aruba SD-WAN OMAN Store','15:00','17:30',2.5,'Remote','Ahmed,Nasif,Sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-09-01','WSR','WSR','13:30','14:00',0.5,'Remote','Ahmed, Sai','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-10-01','Configuration','30923 – Splash Shatea mall, 21522 – Cp Hamdaniya','08:00','11:00',3.0,'Remote','Ahmed, Rishal,Salman','Ahmed Ali, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2026-10-01','Troubleshooting','Application issue and whitelisting break out traffic','13:00','14:00',1.0,'Remote','Ahmed, Rishal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-12-01','Configuration','Oman security policies creation','14:00','16:30',2.5,'Remote','Ahmed, sakib, nasif, Afsal','Ahmed Ali, Mohammed Nasif, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-12-01','Migration','oman store OM-SDWAN-60246 Migration','08:00','12:15',4.25,'Remote','Ahmed, sakib, haneef, nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-12-01','Migration','KSA Store migration','05:30','11:00',5.5,'Remote','Ahmed, Afsal, Rishal','Ahmed Ali, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/13/26','Migration','KSA Store migration','05:30','10:00',4.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/14/26','Migration','KSA Store migration','05:30','11:00',5.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/14/26','Configuration','Oman stores deploymet page configuration','15:00','17:30',2.5,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','1/15/26','Migration','KSA Store migration','05:30','11:00',5.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/17/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/18/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/19/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/20/26','Migration','KSA Store migration','06:00','12:30',6.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/21/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/22/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/22/26','troubleshooting','Tunnel issue troubleshoot call with TAC.','12:00','14:00',2.0,'Remote','Afsal, Rishal, Venkat, Mahesh(TAC)','Mohammed Afsal, Venkatesan','Mohammed Nasif'),
('LANDMARK','1/22/26','Migration','Kuwait Al rai store migration','09:00','16:00',7.0,'Remote','Sakib, ahmed, nasif, nagaraj','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','1/22/26','Migration','Kuwait Al rai store migration','15:00','19:30',4.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/23/26','troubleshooting','Kuwait LM_EXT Store issue','14:45','15:45',1.0,'Remote','Nasif, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','1/22/26','Migration','KSA Store migration','15:00','19:30',4.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/24/26','Migration','KSA Store migration','07:30','11:00',3.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/25/26','Migration','KSA Store migration','07:30','11:00',3.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/25/26','troubleshooting','21532-LM_Retail Issue','13:00','13:30',0.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/26/26','Migration','KSA Store migration','07:00','11:00',4.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/26/26','troubleshooting','DHCP issue in store 21132 call with TAC','03:00','03:30',0.5,'Remote','Afsal, Krishna Chandar','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/26/26','Migration','KSA Store migration','04:30','07:00',2.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/27/26','Migration','KSA Store migration and peer priority issue','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/27/26','Discussion','KSA 500mbps link onboarding discussion','14:00','14:30',0.5,'Remote','Afsal, Ahmed, Rishal, Shaisab','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/28/26','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/28/26','troubleshooting','DHCP issue in store 21132 call with TAC','15:00','15:45',0.75,'Remote','Afsal, Rishal, Krishna','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/29/26','Migration','KSA Store migration','06:30','11:00',4.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-01-02','Migration','KSA Store migration','06:30','11:00',4.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-01-02','Discussion','Aruba SD-WAN || WMS DR Tunnel Creation for Kuwait and Qatar','11:00','13:45',2.75,'Remote','Salman, Afsal, Nagaraj, Rishal','Salman Aziz, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-02-02','Migration','KSA Store migration','06:30','12:00',5.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-03-02','Migration','KSA Store migration','00:00','07:30',7.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-03-02','Migration','OMAN 5  stores migration','07:00','14:00',7.0,'Remote','Nasif, ahmed, sakib','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-04-02','Migration','KSA Store migration','06:00','11:00',5.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-09-02','troubleshooting','ICMP Enabling from EC towards API Gateway','10:15','10:45',0.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-10-02','troubleshooting','Footfall Sensor FTP Issue in SDWAN Store','10:00','11:00',1.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-09-02','troubleshooting','Error: Transaction retrieval unavailable error in SDWAN stores','16:00','18:00',2.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-10-02','troubleshooting','Aruba SDWAN EC1 and EC2 Failover Issue','12:30','13:30',1.0,'Remote','Afsal, salman,Rishal,shaisab,Hussain idris','Mohammed Afsal, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2026-10-02','troubleshooting','FW: KSA Multiple Store network flap Issue - Troubleshooting Call','17:00','19:00',2.0,'Remote','afsal, Salman, Nagaraj, Rishal','Mohammed Afsal, Salman Aziz','Mohammed Nasif'),
('LANDMARK','2026-11-02','Documentation','HLD for WMS tunnel','12:00','14:00',2.0,'Remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','1/13/26','Migration','Alkhuwair Oasis','08:00','12:15',4.25,'Remote','Ahmed,Nasif,Sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','1/20/26','Migration','Store SX - Mabella Mall of Muscat/Store MX - Mabella Mall of Muscat','07:00','12:15',5.25,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/21/26','Migration','HC Oasis Mall, Al-Khuwair','07:00','09:00',2.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/22/26','Migration','MX - Ibri','07:00','10:00',3.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/28/26','Migration','CP Oman Avenues Mall Bawshar/Max Oman Avenues Mall Bawshar','07:00','10:00',3.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','1/29/26','Migration','CP -Mall Oman Mabella/CP - Alkhuwair','07:00','11:00',4.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-01-02','Migration','CP Bawshar Mall of Oman,Max - Bawshar Mall of Oman,HC - Bawshar Mall of Oman – 40099','07:00','11:00',4.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-02-02','Migration','CP-Seeb – 21026,Max Muscat City Centre - 60029,HC – Seeb - 40016,SX - Seeb Muscat City Centre 17160','07:00','13:00',6.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-03-02','Migration','CP - Sohar Oasis,HC - Sohar Oasis,MX - Sohar Oasis,SX - Sohar Oasis,MX - Sohar City Center','07:00','14:00',7.0,'Remote','Ahmed,Nasif,Sakib','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-04-02','Migration','MX,BS,SX - Barka,HC - Clearance Store, Barka','07:00','12:00',5.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-05-02','Migration','CP - Nizwa,MX - Nizwa,HC - Nizwa,SX - Nizwa,MX - Ibri','07:00','14:30',7.5,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-12-02','Pre-migration','WMS tunnel setup call','10:00','11:30',1.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/13/26','Migration','WMS DR setup call','09:00','11:00',2.0,'Remote','Afsal, Rishal, Nagaraj,Ahmed','Mohammed Afsal, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2/15/26','troubleshooting','Traceroute not working from store to HO','14:30','16:00',1.5,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/16/26','troubleshooting','Traceroute not working from store to HO','14:30','16:30',2.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/17/26','troubleshooting','Traceroute not working from store to HO','11:00','12:00',1.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/17/26','Training','Aruba SDWAN-NOC Session','14:30','15:00',0.5,'Remote','Afsal,Rishal,Nagaraj,Afzal,TCS team','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/17/26','troubleshooting','Jeddah SDWAN EC1 & EC2 Issue - Inet','15:00','16:00',1.0,'Remote','Afsal, Rishal, Nagaraj,Shaisab','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/19/26','troubleshooting','Traceroute not working from store to HO(TAC)','14:00','16:00',2.0,'Remote','Afsal, Rishal, Rakshith','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2/23/26','Configuration','Kuwait store devices initial configuration','11:00','15:00',4.0,'Remote','Nasif, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2/24/26','Configuration','Kuwait store devices initial configuration','11:30','15:00',3.5,'Remote','Nasif, sakib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2/26/26','Configuration','QATAR Stores Initial configuration','12:00','15:00',3.0,'Remote','Nasif, sandib','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-02-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-03-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-04-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-05-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-02-03','Discussion','Kuwait WH discussion','12:00','12:30',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-02-03','Migration','Oman-new store migration','13:00','13:30',0.5,'Remote','Ahmed, Nagaraj,Sakib,Nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-04-03','Discussion','Kuwait WH discussion','13:00','13:30',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-05-03','Discussion','Oman WH discussion','12:00','12:30',0.5,'Remote','Ahmed, Nagaraj,Sakib,Ruchika','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-09-03','Configuration','Oman initial provisioning','14:00','15:00',1.0,'Remote','ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-09-03','Documentation','LLD Documentation dammam','11:00','15:00',4.0,'Remote','Nasif','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2026-09-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Nasif,ahmed','Mohammed Nasif, Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-10-03','Documentation','LLD Documentation Riyadh','10:00','15:00',1.0,'Remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-11-03','Documentation','LLD Documentation Jeddah','10:00','15:00',5.0,'Remote','Afsal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-12-03','Migration','KSA Dammam MC Khafji store migration','10:30','13:30',3.0,'Remote','Afsal, Rishal','Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','2026-10-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-11-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-12-03','Daily Sync Call','Daily Sync Call','10:30','11:00',0.5,'Remote','Ahmed, Nagaraj,Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-09-03','Configuration','Oman WH FW Policies creation','14:00','15:00',1.0,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-10-03','Configuration','Oman WH FW Policies creation','11:00','14:30',3.5,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-12-03','Configuration','Aruba Sdwan Landmark Qatar','11:00','14:30',3.5,'Remote','Ahmed,sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/23/26','Daily Sync Call','Daily Sync Call','10:30','10:45',0.25,'Remote','Venkat, nasif','Venkatesan, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','3/24/26','Daily Sync Call','Daily Sync Call','10:30','10:45',0.25,'Remote','Ahmed,nasif','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','3/25/26','Daily Sync Call','Daily Sync Call','10:30','10:45',0.25,'Remote','Ahmed','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/25/26','Discussion','Qatar stores migration planning','12:00','12:30',0.5,'Remote','Ahmed, nasif, afsal','Ahmed Ali, Mohammed Nasif, Mohammed Afsal','Mohammed Nasif'),
('LANDMARK','3/25/26','Configuration','KWT WH policy creation','14:30','16:30',2.0,'Remote','Ahmed, nasif, sakib , anand','Ahmed Ali, Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','3/30/26','Acitivity','KWT Store migration','07:00','12:00',5.0,'Remote','Ahmed, sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/31/26','Configuration','UAE stores initial configuration','09:30','14:00',4.5,'Remote','Nasif, thakiyudheen','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','3/26/26','Configuration','Kuwait WH Discussion','12:30','13:00',0.5,'Remote','Ahmed,Ruchika,Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','3/31/26','Testing','LMG-KUWAIT-Store Connectivity Test','14:30','17:00',2.5,'Remote','Ahmed, Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-01-04','Migration','Rollout Aruba Sdwan Kuwait','08:00','15:00',7.0,'Remote','Ahmed, Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-01-04','Configuration','KONG Subnet added to SDWAN HUB for KSA','17:30','18:30',1.0,'Remote','Ahmed,Nagaraj,Shaisaab,Afzal','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-02-04','Migration','Rollout Aruba Sdwan Kuwait','07:30','13:00',5.5,'Remote','Ahmed, Sakib','Ahmed Ali','Mohammed Nasif'),
('LANDMARK','2026-02-04','Configuration','Initial configuration of devices','09:30','13:30',4.0,'Remote','Nasif, thakiyudheen','Mohammed Nasif','Mohammed Nasif'),
('LANDMARK','2001-03-04','Configuration','Initial configuration of devices','09:30','12:00',2.5,'Remote','Nasif, Thakiyudheen','Mohammed Nasif','Mohammed Nasif');