-- ═══════════════════════════════════════════════════════════════════
-- NetSec Portal — full database schema
-- Last refreshed: 2026-05-22 for v91 (team_members table + trigger).
-- Originally generated from project rxxcrlobbtlvjgcqgjjm by querying
-- the Postgres catalog (see docs/disaster-recovery.md).
-- DISCIPLINE: refresh this file in the SAME commit as any DDL-changing
-- migration. See memory/schema_sql_sync_discipline.md.
--
-- TARGET: a fresh Supabase project (NOT vanilla Postgres). This file
-- references the auth.users table that Supabase ships by default; on
-- vanilla Postgres the user_profiles FK in section 5 will fail.
--
-- APPLY ORDER inside this file:
--   1. Extensions
--   2. RLS helper functions (current_employee_name, is_manager_user)
--   3. Trigger functions
--   4. Tables (column-only — no FKs yet, so order doesn't matter here)
--   5. Constraints — primary keys, unique, check
--   6. Foreign keys (all tables now exist)
--   7. Indexes
--   8. RLS enable + policies
--   9. Triggers
--
-- USAGE: paste into Supabase Studio → SQL Editor on an empty project
--        and run. Or psql -f docs/schema.sql.
--
-- After this, apply the data dump from a Full Backup .zip
-- (netsec-backup-<DATE>.sql) the same way. See docs/disaster-recovery.md
-- for the full restoration procedure.
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. EXTENSIONS ──────────────────────────────────────────────────
-- Supabase pre-installs supabase_vault; included here as a no-op for
-- vanilla Postgres compatibility. plpgsql is always present.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- ── 2. RLS HELPER FUNCTIONS ────────────────────────────────────────
-- Both are STABLE + SECURITY DEFINER so they can read user_profiles
-- without recursing into their own RLS policies. RLS policies on every
-- other table call into these — they must exist before the policies.

CREATE OR REPLACE FUNCTION public.current_employee_name() RETURNS text
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT employee_name FROM public.user_profiles
  WHERE LOWER(email) = LOWER(auth.jwt()->>'email')
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.is_manager_user() RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT COALESCE(
    (SELECT is_manager FROM public.user_profiles
     WHERE LOWER(email) = LOWER(auth.jwt()->>'email') LIMIT 1),
    FALSE
  );
$$;

-- ── 3. TRIGGER FUNCTIONS ───────────────────────────────────────────

-- Stamp employee_skills.updated_at on every UPDATE.
CREATE OR REPLACE FUNCTION public._employee_skills_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- v91: stamp team_members.updated_at on every UPDATE.
CREATE OR REPLACE FUNCTION public._team_members_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- v93: stamp tasks.updated_at on every UPDATE.
CREATE OR REPLACE FUNCTION public._tasks_touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- v72 + v76: defense-in-depth for the engagements UPDATE flow.
-- Server-side stamps tracker_updated_at + updated_by on every update.
-- For non-manager updates, silently reverts every manager-only column to
-- its OLD value. Combined with the engagements_update RLS policy this
-- means an employee can edit only the fields they're supposed to —
-- even if they call the API directly.
CREATE OR REPLACE FUNCTION public.enforce_engagement_employee_edit_perms()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  NEW.tracker_updated_at := now();
  NEW.updated_by         := current_employee_name();

  IF is_manager_user() THEN
    RETURN NEW;
  END IF;

  NEW.status               := OLD.status;
  NEW.owner_employee       := OLD.owner_employee;
  NEW.name                 := OLD.name;
  NEW.type                 := OLD.type;
  NEW.customer_id          := OLD.customer_id;
  NEW.country              := OLD.country;
  NEW.partner              := OLD.partner;
  NEW.start_date           := OLD.start_date;
  NEW.end_date             := OLD.end_date;
  NEW.license_expiry       := OLD.license_expiry;
  NEW.signed_off_on        := OLD.signed_off_on;
  NEW.project_order_no     := OLD.project_order_no;
  NEW.converted_to_project := OLD.converted_to_project;
  NEW.is_archived          := OLD.is_archived;
  NEW.archived_at          := OLD.archived_at;

  RETURN NEW;
END;
$$;

-- ── 4. TABLES ──────────────────────────────────────────────────────
-- Identity columns standardised to GENERATED BY DEFAULT AS IDENTITY —
-- the original schema had a mix of DEFAULT nextval(...) and various
-- identity declarations; this single form behaves the same and avoids
-- the bootstrap problem of creating named sequences before the tables
-- that reference them. The data dump's OVERRIDING SYSTEM VALUE still
-- works (it's a no-op on BY DEFAULT identity columns, required on
-- ALWAYS identity columns).

CREATE TABLE public.user_profiles (
  email text NOT NULL,
  user_id uuid,
  employee_name text NOT NULL,
  is_manager boolean DEFAULT false,
  -- v95: drives the dashboard backup-staleness banner. Only Venkat +
  -- Nasif default to true; backup_log INSERT is gated on this flag.
  is_backup_responsible boolean NOT NULL DEFAULT false,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  status text DEFAULT 'active'::text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.vendors (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NOT NULL,
  display_order integer DEFAULT 100,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.product_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  vendor_id bigint,
  name text NOT NULL,
  display_order integer DEFAULT 100,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  is_gulfit_relevant boolean DEFAULT false NOT NULL
);

CREATE TABLE public.engagements (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id bigint,
  name text NOT NULL,
  type text NOT NULL,
  status text DEFAULT 'active'::text,
  created_by text,
  created_at timestamptz DEFAULT now(),
  country text,
  partner text,
  category text,
  project_order_no text,
  start_date date,
  end_date date,
  tracker_status text,
  orch_version text,
  ec_version text,
  license_expiry date,
  signed_off_on date,
  owner_employee text,
  tracker_remarks text,
  tracker_updated_at timestamptz,
  updated_by text,
  vendor text,
  product_line text,
  converted_to_project boolean DEFAULT false NOT NULL,
  is_archived boolean DEFAULT false NOT NULL,
  archived_at timestamptz
);

CREATE TABLE public.engagement_milestones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  engagement_id bigint NOT NULL,
  sequence integer DEFAULT 1 NOT NULL,
  name text NOT NULL,
  target_date date,
  completed_date date,
  status text DEFAULT 'pending'::text NOT NULL,
  target_count integer,
  actual_count integer,
  notes text,
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE public.amc_contracts (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id bigint,
  customer_name text NOT NULL,
  partner text,
  region text,
  vendor text,
  git_sales_order text,
  amc_value_usd numeric(12,2),
  amc_start_date date NOT NULL,
  amc_end_date date NOT NULL,
  booking_year integer,
  notes text,
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  is_archived boolean DEFAULT false NOT NULL,
  archived_at timestamptz
);

CREATE TABLE public.amc_contract_engagements (
  contract_id bigint NOT NULL,
  engagement_id bigint NOT NULL,
  linked_at timestamptz DEFAULT now()
);

CREATE TABLE public.ps_deals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  client_name text NOT NULL,
  partner text,
  region text,
  mode text,
  vendor text,
  quoted_year integer,
  quoted_month integer,
  awarded_year integer,
  man_days numeric(6,1),
  ps_quoted_tech_usd numeric(12,2),
  ps_quoted_sales_usd numeric(12,2),
  final_ps_value_usd numeric(12,2),
  status text DEFAULT 'quoted'::text NOT NULL,
  consulted_with_tech text,
  remarks text,
  linked_engagement_id bigint,
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  is_archived boolean DEFAULT false NOT NULL,
  archived_at timestamptz
);

CREATE TABLE public.ps_milestones (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  deal_id bigint NOT NULL,
  sequence_order integer NOT NULL,
  title text NOT NULL,
  amount_usd numeric(12,2),
  payment_received_usd numeric(12,2) DEFAULT 0,
  status text DEFAULT 'not_started'::text NOT NULL,
  expected_completion_date date,
  actual_completion_date date,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  percentage numeric(5,2)
);

CREATE TABLE public.unified_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  session_date date NOT NULL,
  start_time text NOT NULL,
  end_time text NOT NULL,
  session_type text NOT NULL,
  engagement_id bigint,
  customer_name text,
  engagement_name text,
  activity_type text,
  session_info text,
  team_members text,
  stake_holders text,
  mode text,
  remarks text,
  total_hours numeric(5,2) DEFAULT 0,
  office_hours numeric(5,2) DEFAULT 0,
  ot_hours numeric(5,2) DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.ot_sessions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  activity text NOT NULL,
  ot_date date NOT NULL,
  start_time text NOT NULL,
  end_time text NOT NULL,
  day_name text,
  band text,
  rate text,
  duration_hours numeric(5,2),
  credited_hours numeric(5,2),
  created_at timestamptz DEFAULT now(),
  status text DEFAULT 'approved'::text,
  manager_comment text,
  reviewed_by text,
  reviewed_at timestamptz,
  customer_name text,
  project_name text,
  activity_type text,
  source text DEFAULT 'manual'::text,
  source_session_id bigint
);

CREATE TABLE public.annual_leave (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  working_days numeric(4,1) NOT NULL,
  reason text,
  approved_by text,
  leave_type text DEFAULT 'annual'::text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.leave_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  working_days numeric(4,1) NOT NULL,
  reason text,
  status text DEFAULT 'pending'::text,
  manager_comment text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz DEFAULT now(),
  leave_type text DEFAULT 'annual'::text,
  cancelled_at timestamptz,
  cancelled_by text,
  effective_end_date date,
  status_changed_at timestamptz
);

CREATE TABLE public.comp_off_register (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  date_taken date NOT NULL,
  type text NOT NULL,
  days numeric(3,1) NOT NULL,
  approved_by text,
  remarks text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.comp_off_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  request_date date NOT NULL,
  type text NOT NULL,
  days numeric(3,1) NOT NULL,
  related_activity text,
  remarks text,
  status text DEFAULT 'pending'::text,
  manager_comment text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.inventory (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  serial_number text NOT NULL,
  model_no text,
  audit_location text,
  availability_status text DEFAULT 'Available'::text,
  rail_kit text DEFAULT 'N/A'::text,
  ids_ps text DEFAULT 'N/A'::text,
  current_location text,
  current_partner text,
  current_end_user text,
  previous_location text,
  version text,
  remarks text,
  audit_date date,
  last_updated_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.inventory_activity_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  device_id bigint,
  serial_number text,
  changed_by text NOT NULL,
  action text NOT NULL,
  field_changes jsonb,
  changed_at timestamptz DEFAULT now()
);

CREATE TABLE public.certificates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee text NOT NULL,
  name text NOT NULL,
  issue_date date NOT NULL,
  expiry_date date NOT NULL,
  file_url text NOT NULL,
  file_name text,
  uploaded_at timestamptz DEFAULT now() NOT NULL,
  is_gulfit_relevant boolean DEFAULT false NOT NULL
);

CREATE TABLE public.employee_skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  employee_name text NOT NULL,
  product_line_id bigint NOT NULL,
  level text NOT NULL,
  last_used_year integer,
  last_used_month integer,
  notes text,
  created_by text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.kb_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  category text,
  tags text,
  content text NOT NULL,
  file_url text,
  submitted_by text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  recipient text NOT NULL,
  type text NOT NULL,
  message text NOT NULL,
  reference_id bigint,
  read_at timestamptz,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE public.dashboard_alert_snoozes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_email text NOT NULL,
  alert_type text NOT NULL,
  alert_ref_id bigint NOT NULL,
  snoozed_at timestamptz DEFAULT now() NOT NULL,
  snoozed_until timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- v91: team members migrated from data/team.json. JSON file kept as
-- offline fallback in js/features/team.js (DB-first, JSON-fallback).
CREATE TABLE public.team_members (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL,
  section text NOT NULL,
  email text,
  phone text,
  country text NOT NULL,
  photo_url text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- v93: general task list. Multi-owner via task_assignments junction.
-- Status check + priority check defined in section 5.
CREATE TABLE public.tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium'::text,
  status text NOT NULL DEFAULT 'yet_to_start'::text,
  start_date date,
  eta_date date,
  end_date date,
  remarks text,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_archived boolean NOT NULL DEFAULT false,
  archived_at timestamptz
);

CREATE TABLE public.task_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  task_id bigint NOT NULL,
  assigned_to text NOT NULL,
  assigned_at timestamptz NOT NULL DEFAULT now()
);

-- v94: Recurring task templates. Templates produce instances in the
-- public.tasks table; the link is tasks.template_id (added below as
-- ALTER) + tasks.frequency + tasks.period_key. last_generated_for is
-- diagnostic only — the authoritative dedup is the unique partial index
-- idx_tasks_template_period in section 7.
CREATE TABLE public.task_templates (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  title text NOT NULL,
  description text,
  priority text NOT NULL DEFAULT 'medium'::text,
  frequency text NOT NULL,
  remarks text,
  is_active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  last_generated_for text
);

CREATE TABLE public.task_template_assignees (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  template_id bigint NOT NULL,
  assigned_to text NOT NULL
);

-- v94: extend tasks with provenance for generated instances.
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS template_id bigint,
  ADD COLUMN IF NOT EXISTS frequency text NOT NULL DEFAULT 'general'::text,
  ADD COLUMN IF NOT EXISTS period_key text;

-- v95: append-only audit log of every Full Backup .zip download.
-- Used by the dashboard staleness banner + Admin Tools "Last backup"
-- pill. No DELETE/UPDATE policies — log is intentionally immutable.
CREATE TABLE public.backup_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  taken_by text NOT NULL,
  taken_by_email text NOT NULL,
  taken_at timestamptz NOT NULL DEFAULT now(),
  file_size_bytes bigint,
  table_count integer,
  row_count integer,
  notes text
);

-- ── 5. PRIMARY KEYS / UNIQUE / CHECK ───────────────────────────────

ALTER TABLE public.user_profiles            ADD CONSTRAINT user_profiles_pkey            PRIMARY KEY (email);
ALTER TABLE public.user_profiles            ADD CONSTRAINT user_profiles_user_id_key    UNIQUE (user_id);

ALTER TABLE public.customers                ADD CONSTRAINT customers_pkey               PRIMARY KEY (id);
ALTER TABLE public.customers                ADD CONSTRAINT customers_name_key           UNIQUE (name);

ALTER TABLE public.vendors                  ADD CONSTRAINT vendors_pkey                 PRIMARY KEY (id);
ALTER TABLE public.vendors                  ADD CONSTRAINT vendors_name_key             UNIQUE (name);

ALTER TABLE public.product_lines            ADD CONSTRAINT product_lines_pkey           PRIMARY KEY (id);
ALTER TABLE public.product_lines            ADD CONSTRAINT product_lines_vendor_id_name_key UNIQUE (vendor_id, name);

ALTER TABLE public.engagements              ADD CONSTRAINT engagements_pkey             PRIMARY KEY (id);
ALTER TABLE public.engagements              ADD CONSTRAINT engagements_customer_id_name_type_key UNIQUE (customer_id, name, type);
ALTER TABLE public.engagements              ADD CONSTRAINT engagements_type_check
  CHECK (type = ANY (ARRAY['project'::text, 'poc'::text, 'amc'::text, 'support'::text, 'presales'::text]));
ALTER TABLE public.engagements              ADD CONSTRAINT engagements_tracker_status_check
  CHECK ((tracker_status IS NULL) OR (tracker_status = ANY (ARRAY[
    'Yet to start'::text, 'Kick-off'::text, 'HLD Discussion'::text, 'HLD Documentation'::text,
    'LLD Discussion'::text, 'LLD Documentation'::text, 'Initial Configuration'::text,
    'Pilot Sites Rollout'::text, 'Migration'::text, 'KT / Training'::text,
    'As-Built Documentation'::text, 'Troubleshooting'::text, 'On demand request'::text])));

ALTER TABLE public.engagement_milestones    ADD CONSTRAINT engagement_milestones_pkey   PRIMARY KEY (id);
ALTER TABLE public.engagement_milestones    ADD CONSTRAINT engagement_milestones_status_check
  CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'blocked'::text]));

ALTER TABLE public.amc_contracts            ADD CONSTRAINT amc_contracts_pkey           PRIMARY KEY (id);
ALTER TABLE public.amc_contract_engagements ADD CONSTRAINT amc_contract_engagements_pkey PRIMARY KEY (contract_id, engagement_id);

ALTER TABLE public.ps_deals                 ADD CONSTRAINT ps_deals_pkey                PRIMARY KEY (id);
ALTER TABLE public.ps_deals                 ADD CONSTRAINT ps_deals_status_chk
  CHECK (status = ANY (ARRAY['quoted'::text, 'won'::text, 'in_progress'::text, 'completed'::text, 'lost'::text, 'cancelled'::text]));
ALTER TABLE public.ps_deals                 ADD CONSTRAINT ps_deals_quoted_month_chk
  CHECK ((quoted_month IS NULL) OR ((quoted_month >= 1) AND (quoted_month <= 12)));

ALTER TABLE public.ps_milestones            ADD CONSTRAINT ps_milestones_pkey           PRIMARY KEY (id);
ALTER TABLE public.ps_milestones            ADD CONSTRAINT ps_milestones_status_chk
  CHECK (status = ANY (ARRAY['not_started'::text, 'active'::text, 'awaiting_signoff'::text, 'awaiting_payment'::text, 'completed'::text]));
ALTER TABLE public.ps_milestones            ADD CONSTRAINT ps_milestones_percentage_range
  CHECK ((percentage IS NULL) OR ((percentage >= 0::numeric) AND (percentage <= 100::numeric)));

ALTER TABLE public.unified_sessions         ADD CONSTRAINT unified_sessions_pkey        PRIMARY KEY (id);
ALTER TABLE public.unified_sessions         ADD CONSTRAINT unified_sessions_session_type_check
  CHECK (session_type = ANY (ARRAY['project'::text, 'poc'::text, 'amc'::text, 'support'::text, 'internal'::text, 'presales'::text, 'customer_testing'::text]));

ALTER TABLE public.ot_sessions              ADD CONSTRAINT ot_sessions_pkey             PRIMARY KEY (id);

ALTER TABLE public.annual_leave             ADD CONSTRAINT annual_leave_pkey            PRIMARY KEY (id);

ALTER TABLE public.leave_requests           ADD CONSTRAINT leave_requests_pkey          PRIMARY KEY (id);
ALTER TABLE public.leave_requests           ADD CONSTRAINT leave_requests_status_check
  CHECK (status = ANY (ARRAY['pending'::text, 'needs_review'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text]));

ALTER TABLE public.comp_off_register        ADD CONSTRAINT comp_off_register_pkey       PRIMARY KEY (id);
ALTER TABLE public.comp_off_requests        ADD CONSTRAINT comp_off_requests_pkey       PRIMARY KEY (id);

ALTER TABLE public.inventory                ADD CONSTRAINT inventory_pkey               PRIMARY KEY (id);
ALTER TABLE public.inventory                ADD CONSTRAINT inventory_serial_number_key  UNIQUE (serial_number);

ALTER TABLE public.inventory_activity_log   ADD CONSTRAINT inventory_activity_log_pkey  PRIMARY KEY (id);

ALTER TABLE public.certificates             ADD CONSTRAINT certificates_pkey            PRIMARY KEY (id);

ALTER TABLE public.employee_skills          ADD CONSTRAINT employee_skills_pkey         PRIMARY KEY (id);
ALTER TABLE public.employee_skills          ADD CONSTRAINT employee_skills_employee_name_product_line_id_key UNIQUE (employee_name, product_line_id);
ALTER TABLE public.employee_skills          ADD CONSTRAINT employee_skills_level_chk
  CHECK (level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'expert'::text, 'na'::text, 'to_be_trained'::text, 'under_training'::text]));
ALTER TABLE public.employee_skills          ADD CONSTRAINT employee_skills_month_chk
  CHECK ((last_used_month IS NULL) OR ((last_used_month >= 1) AND (last_used_month <= 12)));
ALTER TABLE public.employee_skills          ADD CONSTRAINT employee_skills_lastused_pair
  CHECK (((last_used_year IS NULL) AND (last_used_month IS NULL)) OR ((last_used_year IS NOT NULL) AND (last_used_month IS NOT NULL)));

ALTER TABLE public.kb_articles              ADD CONSTRAINT kb_articles_pkey             PRIMARY KEY (id);
ALTER TABLE public.notifications            ADD CONSTRAINT notifications_pkey           PRIMARY KEY (id);

ALTER TABLE public.dashboard_alert_snoozes  ADD CONSTRAINT dashboard_alert_snoozes_pkey PRIMARY KEY (id);
ALTER TABLE public.dashboard_alert_snoozes  ADD CONSTRAINT dashboard_alert_snoozes_user_email_alert_type_alert_ref_id_key
  UNIQUE (user_email, alert_type, alert_ref_id);

ALTER TABLE public.team_members             ADD CONSTRAINT team_members_pkey             PRIMARY KEY (id);
ALTER TABLE public.team_members             ADD CONSTRAINT team_members_section_check
  CHECK (section IN ('sales', 'presales', 'post_sales_technical'));
ALTER TABLE public.team_members             ADD CONSTRAINT team_members_country_check
  CHECK (country IN ('UAE', 'KSA'));

ALTER TABLE public.tasks                    ADD CONSTRAINT tasks_pkey                  PRIMARY KEY (id);
ALTER TABLE public.tasks                    ADD CONSTRAINT tasks_priority_check
  CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text]));
ALTER TABLE public.tasks                    ADD CONSTRAINT tasks_status_check
  CHECK (status = ANY (ARRAY['yet_to_start'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text]));

ALTER TABLE public.task_assignments         ADD CONSTRAINT task_assignments_pkey       PRIMARY KEY (id);
ALTER TABLE public.task_assignments         ADD CONSTRAINT task_assignments_task_id_assigned_to_key UNIQUE (task_id, assigned_to);

-- v94: tasks.frequency check (extends section-5 tasks block).
ALTER TABLE public.tasks                    ADD CONSTRAINT tasks_frequency_check
  CHECK (frequency IN ('general','daily','weekly','monthly','quarterly'));

ALTER TABLE public.task_templates           ADD CONSTRAINT task_templates_pkey         PRIMARY KEY (id);
ALTER TABLE public.task_templates           ADD CONSTRAINT task_templates_priority_check
  CHECK (priority IN ('low', 'medium', 'high', 'urgent'));
ALTER TABLE public.task_templates           ADD CONSTRAINT task_templates_frequency_check
  CHECK (frequency IN ('daily', 'weekly', 'monthly', 'quarterly'));

ALTER TABLE public.task_template_assignees  ADD CONSTRAINT task_template_assignees_pkey PRIMARY KEY (id);
ALTER TABLE public.task_template_assignees  ADD CONSTRAINT task_template_assignees_template_id_assigned_to_key UNIQUE (template_id, assigned_to);

ALTER TABLE public.backup_log               ADD CONSTRAINT backup_log_pkey             PRIMARY KEY (id);

-- ── 6. FOREIGN KEYS ────────────────────────────────────────────────

ALTER TABLE public.user_profiles
  ADD CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.product_lines
  ADD CONSTRAINT product_lines_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id) ON DELETE CASCADE;

ALTER TABLE public.engagements
  ADD CONSTRAINT engagements_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id);

ALTER TABLE public.engagement_milestones
  ADD CONSTRAINT engagement_milestones_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE CASCADE;

ALTER TABLE public.amc_contracts
  ADD CONSTRAINT amc_contracts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE RESTRICT;

ALTER TABLE public.amc_contract_engagements
  ADD CONSTRAINT amc_contract_engagements_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.amc_contracts(id) ON DELETE CASCADE;
ALTER TABLE public.amc_contract_engagements
  ADD CONSTRAINT amc_contract_engagements_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE CASCADE;

ALTER TABLE public.ps_deals
  ADD CONSTRAINT ps_deals_linked_engagement_id_fkey FOREIGN KEY (linked_engagement_id) REFERENCES public.engagements(id) ON DELETE SET NULL;

ALTER TABLE public.ps_milestones
  ADD CONSTRAINT ps_milestones_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.ps_deals(id) ON DELETE CASCADE;

ALTER TABLE public.unified_sessions
  ADD CONSTRAINT unified_sessions_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.engagements(id) ON DELETE SET NULL;

ALTER TABLE public.employee_skills
  ADD CONSTRAINT employee_skills_product_line_id_fkey FOREIGN KEY (product_line_id) REFERENCES public.product_lines(id) ON DELETE RESTRICT;

ALTER TABLE public.task_assignments
  ADD CONSTRAINT task_assignments_task_id_fkey FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE;

-- v94: link instance → template. SET NULL preserves history if a
-- template is hard-deleted (Phase 2 only soft-deletes via is_active).
ALTER TABLE public.tasks
  ADD CONSTRAINT tasks_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.task_templates(id) ON DELETE SET NULL;

ALTER TABLE public.task_template_assignees
  ADD CONSTRAINT task_template_assignees_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.task_templates(id) ON DELETE CASCADE;

-- ── 7. INDEXES ─────────────────────────────────────────────────────

CREATE UNIQUE INDEX idx_customers_name_unique         ON public.customers              USING btree (upper(TRIM(BOTH FROM name)));

CREATE INDEX idx_engagements_is_archived              ON public.engagements            USING btree (is_archived);
CREATE INDEX idx_engagement_milestones_engagement_id  ON public.engagement_milestones  USING btree (engagement_id);

CREATE INDEX idx_amc_contracts_customer               ON public.amc_contracts          USING btree (customer_id);
CREATE INDEX idx_amc_contracts_end_date               ON public.amc_contracts          USING btree (amc_end_date);
CREATE INDEX idx_amc_contracts_booking_year           ON public.amc_contracts          USING btree (booking_year);
CREATE INDEX idx_amc_contracts_is_archived            ON public.amc_contracts          USING btree (is_archived);
CREATE INDEX idx_amc_contract_engagements_engagement  ON public.amc_contract_engagements USING btree (engagement_id);

CREATE INDEX idx_ps_deals_client                      ON public.ps_deals               USING btree (client_name);
CREATE INDEX idx_ps_deals_engagement                  ON public.ps_deals               USING btree (linked_engagement_id);
CREATE INDEX idx_ps_deals_status                      ON public.ps_deals               USING btree (status);
CREATE INDEX idx_ps_deals_is_archived                 ON public.ps_deals               USING btree (is_archived);
CREATE INDEX idx_ps_milestones_deal                   ON public.ps_milestones          USING btree (deal_id);
CREATE INDEX idx_ps_milestones_status                 ON public.ps_milestones          USING btree (status);

CREATE INDEX idx_unified_sessions_session_date        ON public.unified_sessions       USING btree (session_date);

CREATE INDEX idx_certificates_employee                ON public.certificates           USING btree (employee);
CREATE INDEX idx_certificates_expiry                  ON public.certificates           USING btree (expiry_date);
CREATE INDEX idx_certificates_is_gulfit_relevant      ON public.certificates           USING btree (is_gulfit_relevant) WHERE (is_gulfit_relevant = true);

CREATE INDEX idx_employee_skills_employee             ON public.employee_skills        USING btree (employee_name);
CREATE INDEX idx_employee_skills_product_line         ON public.employee_skills        USING btree (product_line_id);

CREATE INDEX notifications_recipient_unread           ON public.notifications          USING btree (recipient, read_at);

CREATE INDEX idx_dashboard_alert_snoozes_user_until   ON public.dashboard_alert_snoozes USING btree (user_email, snoozed_until);

-- v91: partial index — only rows the app actually queries (is_active=true).
CREATE INDEX idx_team_members_section_sort            ON public.team_members           USING btree (section, sort_order) WHERE (is_active = true);

-- v93: tasks list is filtered by is_archived=false then sorted by created_at
-- desc; the partial indexes match that exact query shape.
CREATE INDEX idx_tasks_created_at                     ON public.tasks                  USING btree (created_at DESC) WHERE (is_archived = false);
CREATE INDEX idx_tasks_status                         ON public.tasks                  USING btree (status) WHERE (is_archived = false);
CREATE INDEX idx_task_assignments_task_id             ON public.task_assignments       USING btree (task_id);
CREATE INDEX idx_task_assignments_assigned_to         ON public.task_assignments       USING btree (assigned_to);

-- v94: filter by frequency + active when generating instances.
CREATE INDEX idx_task_templates_active                ON public.task_templates         USING btree (frequency, is_active) WHERE (is_active = true);
CREATE INDEX idx_template_assignees_template          ON public.task_template_assignees USING btree (template_id);
-- Dedup guard for generated instances: at most one per template per period.
CREATE UNIQUE INDEX idx_tasks_template_period         ON public.tasks                  USING btree (template_id, period_key) WHERE (template_id IS NOT NULL);

-- v95: ordered scan for "most recent backup" + the dashboard banner query.
CREATE INDEX idx_backup_log_taken_at                  ON public.backup_log             USING btree (taken_at DESC);

-- ── 8. ROW-LEVEL SECURITY ──────────────────────────────────────────
-- Every table has RLS enabled. Policies fall into three patterns:
--   (a) "_authed"   — auth.role() = 'authenticated' (Step 1 RLS, broad).
--   (b) "own/manager" — employee = current_employee_name() OR
--                       is_manager_user() (Step 2 RLS, per-row ownership).
--   (c) manager-only — is_manager_user() (catalog-style tables).
-- See docs/security/rls_step2_per_row_ownership.sql for context.

-- Enable RLS on every table
ALTER TABLE public.user_profiles           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_lines           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagements             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.engagement_milestones   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amc_contracts           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.amc_contract_engagements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ps_deals                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ps_milestones           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unified_sessions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ot_sessions             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.annual_leave            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comp_off_register       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comp_off_requests       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory_activity_log  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificates            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_skills         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kb_articles             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_alert_snoozes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.team_members            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_assignments        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_templates          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_template_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.backup_log              ENABLE ROW LEVEL SECURITY;

-- user_profiles
CREATE POLICY user_profiles_authed ON public.user_profiles FOR ALL
  USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- customers
CREATE POLICY customers_authed ON public.customers FOR ALL
  USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- vendors
CREATE POLICY vendors_select_authenticated ON public.vendors FOR SELECT TO authenticated USING (true);
CREATE POLICY vendors_insert_manager       ON public.vendors FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY vendors_update_manager       ON public.vendors FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY vendors_delete_manager       ON public.vendors FOR DELETE TO authenticated USING (is_manager_user());

-- product_lines
CREATE POLICY product_lines_select_authenticated ON public.product_lines FOR SELECT TO authenticated USING (true);
CREATE POLICY product_lines_insert_manager       ON public.product_lines FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY product_lines_update_manager       ON public.product_lines FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY product_lines_delete_manager       ON public.product_lines FOR DELETE TO authenticated USING (is_manager_user());

-- engagements
CREATE POLICY engagements_select ON public.engagements FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY engagements_insert ON public.engagements FOR INSERT WITH CHECK (is_manager_user());
CREATE POLICY engagements_update ON public.engagements FOR UPDATE USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY engagements_delete ON public.engagements FOR DELETE USING (is_manager_user());

-- engagement_milestones
CREATE POLICY milestones_read_all        ON public.engagement_milestones FOR SELECT TO authenticated USING (true);
CREATE POLICY milestones_insert_manager  ON public.engagement_milestones FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY milestones_update_manager  ON public.engagement_milestones FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY milestones_delete_manager  ON public.engagement_milestones FOR DELETE TO authenticated USING (is_manager_user());

-- amc_contracts
CREATE POLICY amc_contracts_select_authenticated ON public.amc_contracts FOR SELECT TO authenticated USING (true);
CREATE POLICY amc_contracts_insert_manager       ON public.amc_contracts FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY amc_contracts_update_manager       ON public.amc_contracts FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY amc_contracts_delete_manager       ON public.amc_contracts FOR DELETE TO authenticated USING (is_manager_user());

-- amc_contract_engagements
CREATE POLICY amc_contract_engagements_select_authenticated ON public.amc_contract_engagements FOR SELECT TO authenticated USING (true);
CREATE POLICY amc_contract_engagements_insert_manager       ON public.amc_contract_engagements FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY amc_contract_engagements_delete_manager       ON public.amc_contract_engagements FOR DELETE TO authenticated USING (is_manager_user());

-- ps_deals
CREATE POLICY "ps_deals manager only"      ON public.ps_deals      FOR ALL TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());

-- ps_milestones
CREATE POLICY "ps_milestones manager only" ON public.ps_milestones FOR ALL TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());

-- unified_sessions — self-or-manager on writes; any authed can read
CREATE POLICY unified_sessions_select ON public.unified_sessions FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY unified_sessions_insert ON public.unified_sessions FOR INSERT WITH CHECK (is_manager_user() OR (employee = current_employee_name()));
CREATE POLICY unified_sessions_update ON public.unified_sessions FOR UPDATE USING (is_manager_user() OR (employee = current_employee_name())) WITH CHECK (is_manager_user() OR (employee = current_employee_name()));
CREATE POLICY unified_sessions_delete ON public.unified_sessions FOR DELETE USING (is_manager_user() OR (employee = current_employee_name()));

-- ot_sessions
CREATE POLICY ot_sessions_authed ON public.ot_sessions FOR ALL
  USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- annual_leave / leave_requests / comp_off_register / comp_off_requests
CREATE POLICY annual_leave_authed       ON public.annual_leave       FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY leave_requests_authed     ON public.leave_requests     FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY comp_off_register_authed  ON public.comp_off_register  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY comp_off_requests_authed  ON public.comp_off_requests  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- inventory + inventory_activity_log
CREATE POLICY inventory_authed              ON public.inventory              FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY inventory_activity_log_authed ON public.inventory_activity_log FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- certificates — self-or-manager
CREATE POLICY certificates_select_own_or_manager ON public.certificates FOR SELECT TO authenticated USING ((employee = current_employee_name()) OR is_manager_user());
CREATE POLICY certificates_insert_own            ON public.certificates FOR INSERT TO authenticated WITH CHECK (employee = current_employee_name());
CREATE POLICY certificates_update_own_or_manager ON public.certificates FOR UPDATE TO authenticated USING ((employee = current_employee_name()) OR is_manager_user()) WITH CHECK ((employee = current_employee_name()) OR is_manager_user());
CREATE POLICY certificates_delete_own_or_manager ON public.certificates FOR DELETE TO authenticated USING ((employee = current_employee_name()) OR is_manager_user());

-- employee_skills — manager-only
CREATE POLICY "skills manager all" ON public.employee_skills FOR ALL TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());

-- kb_articles
CREATE POLICY kb_authed ON public.kb_articles FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- notifications — recipient-scoped
CREATE POLICY notifications_select ON public.notifications FOR SELECT USING (recipient = current_employee_name());
CREATE POLICY notifications_insert ON public.notifications FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY notifications_update ON public.notifications FOR UPDATE USING (recipient = current_employee_name()) WITH CHECK (recipient = current_employee_name());

-- dashboard_alert_snoozes — per-user via JWT email
CREATE POLICY dashboard_alert_snoozes_select_own ON public.dashboard_alert_snoozes FOR SELECT TO authenticated USING (lower(user_email) = lower(auth.jwt() ->> 'email'));
CREATE POLICY dashboard_alert_snoozes_insert_own ON public.dashboard_alert_snoozes FOR INSERT TO authenticated WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email'));
CREATE POLICY dashboard_alert_snoozes_update_own ON public.dashboard_alert_snoozes FOR UPDATE TO authenticated USING (lower(user_email) = lower(auth.jwt() ->> 'email')) WITH CHECK (lower(user_email) = lower(auth.jwt() ->> 'email'));
CREATE POLICY dashboard_alert_snoozes_delete_own ON public.dashboard_alert_snoozes FOR DELETE TO authenticated USING (lower(user_email) = lower(auth.jwt() ->> 'email'));

-- team_members — broad authenticated read, manager-only write (v91).
CREATE POLICY team_members_select_authenticated ON public.team_members FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY team_members_insert_manager       ON public.team_members FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY team_members_update_manager       ON public.team_members FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY team_members_delete_manager       ON public.team_members FOR DELETE TO authenticated USING (is_manager_user());

-- tasks (v93) — any authenticated user reads; manager-only create/archive;
-- manager OR any assignee can UPDATE (frontend restricts which fields).
CREATE POLICY tasks_select_authenticated ON public.tasks FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY tasks_insert_manager       ON public.tasks FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY tasks_update_manager_or_assignee ON public.tasks FOR UPDATE TO authenticated
  USING (is_manager_user() OR (EXISTS (SELECT 1 FROM public.task_assignments ta WHERE ta.task_id = tasks.id AND ta.assigned_to = current_employee_name())))
  WITH CHECK (is_manager_user() OR (EXISTS (SELECT 1 FROM public.task_assignments ta WHERE ta.task_id = tasks.id AND ta.assigned_to = current_employee_name())));
CREATE POLICY tasks_delete_manager       ON public.tasks FOR DELETE TO authenticated USING (is_manager_user());

-- task_assignments (v93) — manager-managed junction. Authenticated read so
-- the join used by tasks_update_manager_or_assignee works for non-managers.
CREATE POLICY task_assignments_select_authenticated ON public.task_assignments FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY task_assignments_insert_manager       ON public.task_assignments FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY task_assignments_delete_manager       ON public.task_assignments FOR DELETE TO authenticated USING (is_manager_user());

-- task_templates (v94) — authenticated read, manager-only write.
CREATE POLICY task_templates_select_authenticated ON public.task_templates FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY task_templates_insert_manager       ON public.task_templates FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY task_templates_update_manager       ON public.task_templates FOR UPDATE TO authenticated USING (is_manager_user()) WITH CHECK (is_manager_user());
CREATE POLICY task_templates_delete_manager       ON public.task_templates FOR DELETE TO authenticated USING (is_manager_user());

-- task_template_assignees (v94) — authenticated read (needed for embed
-- when generating instances), manager-only insert/delete. No UPDATE
-- policy — assignment edits happen via delete + re-insert.
CREATE POLICY template_assignees_select_authenticated ON public.task_template_assignees FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY template_assignees_insert_manager       ON public.task_template_assignees FOR INSERT TO authenticated WITH CHECK (is_manager_user());
CREATE POLICY template_assignees_delete_manager       ON public.task_template_assignees FOR DELETE TO authenticated USING (is_manager_user());

-- backup_log (v95) — broad authenticated read (Admin Tools pill is
-- informational for everyone); INSERT gated on user_profiles.is_backup_responsible
-- so only Venkat + Nasif can append rows. Log is intentionally append-only:
-- no UPDATE or DELETE policies.
CREATE POLICY backup_log_select_authenticated         ON public.backup_log FOR SELECT TO authenticated USING (auth.role() = 'authenticated');
CREATE POLICY backup_log_insert_backup_responsible    ON public.backup_log FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.user_profiles
    WHERE LOWER(email) = LOWER(auth.jwt() ->> 'email')
      AND is_backup_responsible = true
  ));

-- ── 9. TRIGGERS ────────────────────────────────────────────────────

CREATE TRIGGER trg_employee_skills_touch
  BEFORE UPDATE ON public.employee_skills
  FOR EACH ROW EXECUTE FUNCTION public._employee_skills_touch_updated_at();

CREATE TRIGGER engagement_employee_edit_perms
  BEFORE UPDATE ON public.engagements
  FOR EACH ROW EXECUTE FUNCTION public.enforce_engagement_employee_edit_perms();

-- v91
CREATE TRIGGER trg_team_members_touch
  BEFORE UPDATE ON public.team_members
  FOR EACH ROW EXECUTE FUNCTION public._team_members_touch_updated_at();

-- v93
CREATE TRIGGER trg_tasks_touch
  BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public._tasks_touch_updated_at();

-- v94: same touch function reused for task_templates (both tables just
-- need an updated_at stamp on every UPDATE).
CREATE TRIGGER trg_task_templates_touch
  BEFORE UPDATE ON public.task_templates
  FOR EACH ROW EXECUTE FUNCTION public._tasks_touch_updated_at();

COMMIT;

-- End of schema. Apply the data dump next (netsec-backup-<DATE>.sql).
